// for login 

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// for login 

export const LOGOUT_LOADING = "LOGOUT_LOADING";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";


// get block data
export const FETCHDATA_LOADING = "FETCHDATA_LOADING";
export const FETCHDATA_SUCCESS = "FETCHDATA_SUCCESS";
export const FETCHDATA_FAILURE = "FETCHDATA_FAILURE";


// get individual block data
export const FETCH_INDIVIDUAL_DATA_LOADING = "FETCH_INDIVIDUAL_DATA_LOADING";
export const FETCH_INDIVIDUAL_DATA_SUCCESS = "FETCH_INDIVIDUAL_DATA_SUCCESS ";
export const FETCH_INDIVIDUAL_DATA_FAILURE = "FETCH_INDIVIDUAL_DATA_FAILURE";

